### ISSUE TITLE
Error reading CMEMS ocean data

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#102]
Hi,

I want to use CMEMS ocean data (product GLOBAL_REANALYSIS_PHY_001_030) with the reader_netCDF_CF_generic reader. It gives the following error:

INFO: OpenDriftSimulation initialised (version 1.0.5)
INFO: Opening dataset: /home/mosa/Daniel/vo_1993-2017.nc
INFO: Opening file with Dataset
DEBUG: Finding coordinate variables.
DEBUG: Parsing variable: depth
DEBUG: Parsing variable: latitude
DEBUG: Parsing variable: longitude
DEBUG: Parsing variable: time
DEBUG: Parsing variable: vo
DEBUG: Parsing variable: uo
DEBUG: Lon and lat are 1D arrays, assuming latong projection
DEBUG: Setting buffer size 49 for reader /home/mosa/Daniel/vo_1993-2017.nc, assuming a maximum average speed of 5 m/s.
DEBUG: Setting buffer size 12 for reader /home/mosa/Daniel/vo_1993-2017.nc, assuming a maximum average speed of 1 m/s.
DEBUG: Calculation SRS set to: +units=m +proj=latlong +ellps=WGS84
DEBUG: Using srs for common grid: +proj=latlong
DEBUG: Added reader /home/mosa/Daniel/vo_1993-2017.nc
DEBUG: ------------------------------------------------------
DEBUG: Software and hardware:
DEBUG:   unknown GB memory
DEBUG:   4 processors (x86_64)
DEBUG:   Basemap version 1.0.7
DEBUG:   NumPy version 1.13.3
DEBUG:   SciPy version 0.19.1
DEBUG:   Matplotlib version 2.1.0
DEBUG:   NetCDF4 version 1.2.4
DEBUG:   Python version 2.7.14 |Anaconda, Inc.| (default, Oct 16 2017, 17:29:19) [GCC 7.2.0]
DEBUG: ------------------------------------------------------
INFO: Config validation OK
DEBUG: No output file is specified, neglecting export_buffer_length
INFO: Fallback values will be used for the following variables which have no readers: 
INFO: 	x_wind: 0.000000
INFO: 	y_wind: 0.000000
INFO: Duration, steps or end time not specified, running until end of first reader: 2017-12-26 12:00:00
INFO: Adding a dynamical landmask (resolution "h") based on assumed maximum speed of 1 m/s. Adding a customised landmask may be faster...
DEBUG: Creating Basemap...
Traceback (most recent call last):
  File "./copas_opendrift.py", line 56, in <module>
    o.run(time_step=3600)
  File "/home/mosa/opendrift/opendrift/models/basemodel.py", line 2041, in run
    projection='merc')
  File "/home/mosa/opendrift/opendrift/readers/reader_basemap_landmask.py", line 64, in __init__
    resolution=resolution, projection=projection)
  File "/home/mosa/miniconda2/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 684, in __init__
    self.llcrnrlon = _validated_ll(llcrnrlon, 'llcrnrlon', -360, 720)
  File "/home/mosa/miniconda2/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 501, in _validated_ll
    (name, minval, maxval))
ValueError: llcrnrlon must be between -360.000000 and 720.000000 degrees

**Comment by knutfrode** [comment]
Hi,

First, I recommend to update to the newest version of OpenDrift, as this might possible be a bug which has been fixed in the meantime.

You could also consider to update your dependencies, as several packages are quite outdated, e.g. Basemap 1.0.7. Note that OpenDrift now comes with conda environment files, which ensure consistent versions of all dependencies: https://github.com/opendrift/opendrift/wiki#download-and-installation

Anyway, the problem seems here that a simulation over some longer periode is expected, and OpenDrift tries to guess and make a Basemap for the possibly influenced domain - and this may e.g. exceed longitudes of -360. The first thing to try is to provide an [end time (or duration or number of steps)](https://github.com/OpenDrift/opendrift/wiki/How-to-run-a-trajectory-simulation#5-running-the-model) for your simulation as input to the run() method.
For a simulation over a large domain/period, you might also want to decrease the Basemap resolution, as the default ('h') might be overkill for a large domain. Note that it is also possible to disable the automatic Basemap, and use landmask from e.g. ocean model reader instead.

**Comment by AndresSepulveda** [comment]
Thanks! With a finite number of steps all works well.
