### ISSUE TITLE
Buffer warning and strange trajectories in OceanDrift using reader_netCDF_CF_unstructured

### ISSUE THREAD

**Issue by bmooremaley** [OpenDrift/opendrift#113]
I'm experiencing a buffer size warning accompanied by nonphysical trajectories in my OceanDrift runs when using the unstructured netCDF reader to load my regional ocean model water velocities. Usually about a day into the simulation particles will begin to align in odd patterns (usually meridionally) and move around the domain as a group (as if all being driven by a single velocity point). Around the time this begins (or several timesteps before) I see the following warning:

WARNING: Data block from <filename.nc> not large enough to cover element positions within timestep. Buffer size (0) must be increased.

This behavior is not removed by changing the configuration (drift scheme, timestep, starttime, start location, etc.). I'm using the unstructured reader because my model results are on a rotated grid relative to north-south that is not defined by a projection.

I found that my buffer size is set to the default value of zero and never calculated according to max_speed because the unstructured netCDF reader doesn't assign a delta_x, delta_y pair to the reader object. Increasing this default buffer size value has no effect on the warning or the trajectories (other than changing the value in the warning).

Here is a link to a notebook that provides an example run.
[https://nbviewer.jupyter.org/urls/bitbucket.org/salishsea/analysis-ben/raw/tip/notebooks/sample_opendrift_simulation.ipynb](https://nbviewer.jupyter.org/urls/bitbucket.org/salishsea/analysis-ben/raw/tip/notebooks/sample_opendrift_simulation.ipynb)

I added some plots of the seawater velocities following the particles at the bottom of the notebook. The velocities become small (relative to the strong tidal velocities I would expect) and seem to converge a bit after a few days into the simulation.

**Comment by knutfrode** [comment]
The warning about buffer size may normally be ignored, as it indicates that particles are close to reader boundary/coverage. I will fix that warning one day.

However, the problem here is almost certainly related to the unstructured reader. This reader is far less developed and less robust than the "regular" netCDF-reader. Regular readers have a fixed minimum/maximum values of x and y (or lon/lat), however, this is more complicated for unstructured data. I would believe the problems are related to this, and to the boundary.
I wrote this reader quickly some time back for other users, but have actually never used it myself. Unfortunately I have also not capacity to develop it further within the next 6 months or so.

Thus, my only recommendation would be to try to debug this reader, or hope for help from the "community".
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_netCDF_CF_unstructured.py

**Comment by bmooremaley** [comment]
Okay, I thought this might be the case. Thanks for the quick response! I'll see what I can do.

**Comment by nsoontie** [comment]
@bmooremaley There is a fairly recent changeset that might fix the Buffer warning/unphysical trajectories that you are experiencing.
50904181d11f955954597ada3db88dc496b7a2dd
