### ISSUE TITLE
Reader behavior and non-matching vertical temperature profiles 

### ISSUE THREAD

**Issue by mlicer** [OpenDrift/opendrift#1150]
Dear all,

I am simulating a single linearly sinking particle (sinking 10 m per time step), using a custom class. The class requires ocean temperature profile at particle location.  The simulation runs fine, but since the particle linearly traverses the entire water column, i would expect that the vertical temperature profile in the OpenDrift netCDF output should closely resemble the vertical profile from the temperature input netCDF. The two profiles are however completely different. Vertical advection works fine but the particle doesn't "see" the correct temperature at its depth.

A minimal example to reproduce this is in the link below. 
[https://drive.google.com/drive/folders/1c5byNeF9BiC3cKLTL1mk-lVbgs0MvoTs?usp=drive_link](https://drive.google.com/drive/folders/1c5byNeF9BiC3cKLTL1mk-lVbgs0MvoTs?usp=drive_link)

The code `run_temp.py` can be run in OpenDrift environment with: `./run_temp.py jun_T_crop.nc outfile.nc`
The correct temperature profile is shown in `correct.png`, while the code plots the temperature profile from the output file.

Any comment would be **very** warmly appreciated.
Matjaz

**Comment by knutfrode** [comment]
Thank you for the nicely prepared example, making it efficient to debug!

The issue here is that OpenDrift only reads one extra layer below present deepest position, as normally/often the particle will not go deeper than that within the upcoming time step. However, with this rapid sinking, particles will go deeper than the cached temperature data.
The internal algorithm should be updated here.
However, there is a workaround ready that solves your problem:
the "vertical buffer" is 1 layer by default, but you can specify it after creating the reader:
```
temp = reader_netCDF_CF_generic.Reader(temperature_file)
temp.verticalbuffer=100
```

With this inserted, I get the following plot, which seems correct.
![Figure_1](https://github.com/OpenDrift/opendrift/assets/5222051/1c932c23-9200-48f7-b5c4-1b544faad8f1)

**Comment by mlicer** [comment]
Dear Knut, 

thanks so much for this blazingly fast explanation and fix, it works! Truly grateful!

All the best,
Matjaz

**Comment by mlicer** [comment]
Closing the issue.
