### ISSUE TITLE
Number converted to array

### ISSUE THREAD

**Issue by trondkr** [OpenDrift/opendrift#121]
Hi, if you run this:
`o.seed_elements(lon=st_lons, lat=st_lats, number=2000, radius=[1, 5000], cone=True, time=ti, z=-1000)`

Then in `basemodel.py` on line 1435 in the call `time_array = [time[0] + i*td for i in range(number)]` the `number` has been converted to an array (for some reason) and is no longer a scalar. This can easily be fixed adding:  `if len(number) == 1: number=number[0]` but not very elegant. I expect there is something happening earlier that wrongly converts the scalar to an array.

Using `OpenDrift version 1.0.7`

**Comment by knutfrode** [comment]
Yes, ```number``` is always converted to array, as ```seed_elements()``` calls itself recursively for ```"cones"```.

But an obsolete line provided the error you encountered, which happens when time is an array with length equal to the number of elements.

This is now removed/fixed: https://github.com/OpenDrift/opendrift/commit/3383f679cc86081054e8b12c1c67e408640f18cc
