### ISSUE TITLE
Recording the final position of deactivated particles

### ISSUE THREAD

**Issue by CaroMedel** [OpenDrift/opendrift#1249]
Hi,

I'm working with the stranding method for coastal interaction. Is it possible for deactivated particles to continue recording their last horizontal and vertical positions? By default, when a particle is deactivated, its variables lon, lat and z become a huge number. I would like them to record their last position until the end of simulation. Is that possible?

Best,
Caro

**Comment by CaroMedel** [comment]
Thanks for your quick response. But I don't wan to to filter away the deactivated particles. I'm reviewing a specific time and I want to check the position of activated particles and deactivated ones as well. Not for visual purposes, but for analysis

Caro

**Comment by knutfrode** [comment]
When using `o.get_property()` the NaN-values are filled with the last value before deactivation:
https://opendrift.github.io/_modules/opendrift/models/basemodel.html#OpenDriftSimulation.get_property

In the future, the writing to file will probably be changed so that the last value is written also after deactivation.

**Comment by CaroMedel** [comment]
I'm not using python for this analysis. But I solved it during the post-processing of the output.

Thanks
