### ISSUE TITLE
global model (HYCOM) problem

### ISSUE THREAD

**Issue by ivicajan** [OpenDrift/opendrift#1324]
Dear developers,
In the gallery (documentation) you have an example with HYCOM global model that is not worling. LInk to the TDS is not valid
https://opendrift.github.io/gallery/example_long_global_thredds.html as they changed  it long time ago 
https://tds.hycom.org/thredds/dodsC/GLBy0.08/latest
into: 
https://tds.hycom.org/thredds/dodsC/GLBy0.08/expt_93.0/FMRC/GLBy0.08_930_FMRC_best.ncd

This link was working until week ago, but now giving errors. Anyone having similar experience?
p.s. you can ncdump -h the last link to have idea about the format. Strange added dimension time1 might be a problem?

Regards,
Ivica

**Comment by knutfrode** [comment]
Hi Ivica, and thank you for the notification.
Yes, I also noticed problems with hycom-thredds the last week.

In fact, we used the [FMRC several years ago](https://github.com/OpenDrift/opendrift/issues/96), but then later changed to https://tds.hycom.org/thredds/dodsC/GLBy0.08/latest, but this seem to have been decommisioned sinced 6th June.


Testing now with the FMRC aggregate, it sometimes works partly, and sometimes not. Thus there seem to be some issues with the server or the underlying data files.
Let's hope for a fix, as there seem to be no other global forecasts on tds.hycom.org

**Comment by knutfrode** [comment]
It seems that this URL works well, and contains both history since 2023 and a forecast:
https://www.ncei.noaa.gov/thredds-coastal/dodsC/hycom/hycom_sfc_agg/HYCOM_Surface_Aggregation_best.ncd

So I now replaced the to old tds.hycom.org URLs with this one:
https://github.com/OpenDrift/opendrift/pull/1326/files#diff-bee6fdd6382d055b008ee978f9e38d213dc52b8ed4f0be957e136df3d7b2fbd7
