### ISSUE TITLE
Usage of OpenDrift while using LSC2 vertical layer in SCHISM

### ISSUE THREAD

**Issue by simonweppe** [OpenDrift/opendrift#1361]
From "Jae-Soon JEONG" - 

Actually, I noticed that there is no change in variables' names between sigma coordinates and LSC2 coordinates.
So, I just ran OpenDrift with SCHISM outputs with LSC2 as a test and it worked and gave me OpenDrift results anyway.
I will check whether the results are reasonable scientifically.

Please let me check one more thing.

![unnamed](https://github.com/OpenDrift/opendrift/assets/7277011/55f28e3e-86f7-435d-adcb-23f10542dc85)

In this script (reader_schism_native.py), the code is importing 'zcor' and 'sigma' from SCHISM outputs, which are related to vertical layers.
These matrix sizes are,
zcor(time, nSCHISM_hgrid_node, nSCHISM_vgrid_layers)
sigma(sigma).

As you explained, zcor seems to deliver the 3-D information of time-varying vertical coordinates to OpenDrift. 

How about 'sigma'? 
I cannot find any source code using the variables 'sigma' or 'ocean_s_coordinate' in the OpenDrift code.
Can I know why this variable was imported?
In the case of sigma coordinates, the 'sigma' has values of [-1, -0.97, -0.93, -0.9 ..... -0.1, -0.07, -0.03, 0]. It increased from -1 to 0 with an increment of 0.03333 because I defined 30 layers.
However, in the case of LSC2 coordinates, the 'sigma' has 0 values because it is not a sigma coordinate. 

If the 'simga' variable is not used in OpenDrift, it seems that the SCHISM results with LSC2 can be used in OpenDrift without any additional modification.

Thanks for your help.

**Comment by knutfrode** [comment]
Hi,
I am normally not using unstructured data myself, and have never used the schism reader, although I believe I added some minor updates some time ago. Thus I have no deep insight into how this particular reader works, but I can confirm that OpenDrift expects a reader to return a dictionary with the data variables, and 1D coordinate variables 'x', 'y', and 'z'.
Thus each reader is responsible to convert eventual sigma layers to z-layers internally, if necessary/relevant, before returning the `variables`dictionary.

Ideally one would like to "centralize" this task, so that `sigma` could also be returned as coordinate from a reader, to be converted to z-levels e.g. within `basereader`. However, I guess that one then also would need to include the corresponding seafloor depth, and possible some other variables(?). There is no immediate plan to implement this feature, but any contributions/pull requests in this direction would be welcome. But it would require some fundamental changes and thus careful planning.

Anyway, it does not seem like the `sigma` variable is used within the schism reader, and thus it could be removed from the mapping to avoid reading it unnecessarily.

**Comment by simonweppe** [comment]
@knutfrode yes sorry, I should have explained that I just opened the ticket for Jae-Soon JEONG for him to follow up after some exchanges we had on the SCHISM forum where he was asking that SCHISM reader in Opendrift.

I think he managed to get it working in the end so it's probably fine to close the comment.

I have made some more tweaks to my version of the reader in my fork - will try to clean/document better and propose a PR.

Thanks
