### ISSUE TITLE
Final location

### ISSUE THREAD

**Issue by Jallel30** [OpenDrift/opendrift#140]
Hello everyone,
I wanted to know if by saving just the last day of a simulation the particles stranded in the past days keep saved in the final file?

thanks!

**Comment by AndresSepulveda** [comment]
To clarify, if we do set the output_time_step to one day but the time_step to one hour, we will not know at what time of the day it was stranded (but the stranding location will be ok). Is this correct?

**Comment by knutfrode** [comment]
Yes, that is correct. It will be stranded at correct location (during an internal calculation time step), but you lose information about at which internal time step this happened.
Though I believe this information can be derived from property ```age_seconds```which will be frozen after deactivation.

So, in general it is recommended to have small calculation time step so that particles do not jump far onto land. But you may still use larger output time step to save disk space and memory.

**Comment by gauteh** [comment]
Closing, seems to be solved.
