### ISSUE TITLE
oil in ice

### ISSUE THREAD

**Issue by llx206** [OpenDrift/opendrift#149]
hello
1.	Can the Opendrift simulate the case of oil in ice? 
2.	What variables about ice is needed when simulate the transport of oil in ice?
3.	In example_oil_ice.py, only the variable sea_ice_area_fraction of ice is considered and the value lager than 0.6 the oil particles will stop move. Ice cover affects the transport of oil, and how deal with the movement of oil in the presence of ice in the Opendrift?
Thanks in advance

**Comment by knutfrode** [comment]
The present oil drift module is very simplistic regarding ice. The only effect is what you describe, that oil particles are deactivated when the ice fraction is above 60%. 
Instead of deactivating the oil, advection of oil with the sea ice drift will soon be implemented. No more sophisticated oil-ice-interaction is foreseen in the nearest future.

**Comment by llx206** [comment]
Thank you very much!
The article ‘Improving oil spill trajectory modelling in the Arctic’ maybe can serves as a reference for advancement of oil-ice module.

**Comment by gauteh** [comment]
I think this issue can be closed now. An improved sea-ice drift with oil has been implemented and included.
