### ISSUE TITLE
Uniform seeding of elements

### ISSUE THREAD

**Issue by Lovisasvensson** [OpenDrift/opendrift#272]
HI! I use and work with a clone of opendrift. Recently, I had to implement a new feature to the code in order to get it working as I wanted. I'm not sure whether this is something you would like to consider for the official Opendrift. So I just present it as a suggestion. If you include it, it would be good for me for future work when I might want to use a newer version of Opendrift. 

The fix is for to get uniform seeding of the elements. The fix is in basemodel.py, in the function seed_elements(). I changed the two rows
x = np.random.randn(number)*radius 
y = np.random.randn(number)*radius 
to:
length = radius * np.random.rand(number) 
angle = 2 * np.pi * np.random.rand(number) 
x = length * np.cos(angle) 
y = length * np.sin(angle) 

Also I'm not sure if you aware of that your seeding is more box-like rather than circular as the variable name 'radius' implies. If you would like a circular normal-distributed seeding I think it should be:
length = radius * np.random.randn(number) 
angle = 2*np.pi * np.random.rand(number) 
x = length * np.cos(angle) 
y = length * np.sin(angle)
Maybe it would be nice to implement different options of this for the user. 

Sorry, I know there might be more convenient ways of communicate code-fixes rather than here, but  this was easier for me since I'm a semi-beginner at this.

/Lovisa

**Comment by knutfrode** [comment]
Hi Lovisa,

I added now the possibility to provide  ```radius_type='uniform'``` to ```seed_elements()``` so that elements will be seeded uniformly (but randomly) within a circle with the given radius.
https://github.com/OpenDrift/opendrift/commit/7eb0c21d5a349f5ba8c8bba8de126932953f8066
I believe this is what you want?

For the existing/default seeding, ```radius``` is not an absolute bound, but a gaussian standard deviation in x- and y-directions. This also provides a circular (and not box-like) distribution (yielding a Rayleigh distribution of absolute radii), but elements are denser close to the center (which is often desired, e.g. for search and rescue), but may then also be found at a very large distance away.

Hopefully it is ok to build your clone on top of this?

**Comment by Lovisasvensson** [comment]
Thank you! I think that's just what I was looking for.
