### ISSUE TITLE
Sinking particles

### ISSUE THREAD

**Issue by stefraynaud** [OpenDrift/opendrift#35]
In the following example, I can't make particles to sink below -120m.
Why ?
```python
from opendrift.models.openoil3D import OpenOil3D
import logging
from datetime import datetime, timedelta

o = OpenOil3D(loglevel=logging.WARNING)

o.seed_elements(lon=-50, lat=40., z=-20, number=10, density=1300.,
    time=datetime.now(), diameter=0.001)

o.run(time_step=30, duration=timedelta(hours=.5))
o.animation_profile(markersize=10)
```

**Comment by knutfrode** [comment]
This is because vertical profiles of ocean data are by default only read
from surface and down to 120 metres:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/openoil3D.py#L71

But you can override this by inserting this line before you start the run:
o.required_profiles_z_range = [-500, 0]  # Allowing turbulence down to 500 m

Note that the process is not direct sinking (droplets are buoyant), but
vertical turbulent mixing.

2017-02-08 7:50 GMT-06:00 Stephane Raynaud <notifications@github.com>:

**Comment by stefraynaud** [comment]
Thanks alot for your answer. It works now.

As for the buoyancy, I chose a density greater than water!
