### ISSUE TITLE
Question on structuring a landmask file

### ISSUE THREAD

**Issue by Gui-Marinho** [OpenDrift/opendrift#359]
Hello,

I am working on applying opendrift to a Great Lakes setting. I have a high accuracy landmask in ASCII format, and am working on adapting it to netCDF format. I am wondering what components does opendrift require out of this file? 
So far I have gathered it needs to have:
latitude and longitude dimensions, and a land_binary_mask variable with 0s for sea and 1s for land
should I have latitude and longitude variables with the coordinates of each point? Am I missing any other components?

Thanks for your attention,
Guilherme

**Comment by knutfrode** [comment]
Hi,

I assume this landmask is a vector, and not a raster?
If so, it is better to make a shapefile rather than netCDF. 
However, there are some ready made shapefiles available online, e.g. this one:
http://gis-michigan.opendata.arcgis.com/datasets/6031c4fb8cac48649f2e0a98999d1248_0  (Download -> Shapefile)

With this downloaded and unzipped, it may be used as in the example code/plot below:

```
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from opendrift.readers import reader_shape
from opendrift.models.oceandrift import OceanDrift

o = OceanDrift()
reader_lake = reader_shape.Reader.from_shpfiles('Great_Lakes.shp', invert=True)
o.add_reader(reader_lake)
o.set_config('general:use_auto_landmask', False)
o.seed_elements(lon=-86.5, lat=45.5, radius=3000, number=1000,
                time=datetime.now())
o.fallback_values['x_sea_water_velocity'] = 2
o.run(time_step=600, duration=timedelta(hours=48))

# Making plot without landmask, and returning handles so that we can add s
hapes manually
ax, _ = o.plot(hide_landmask=True, show=False, buffer=3)
ax.add_geometries(reader_lake.polys, ccrs.PlateCarree(), facecolor=cfeature.COLORS['land'], edgecolor='black')
plt.show()
```

![Greatlakes](https://user-images.githubusercontent.com/5222051/91491311-2625f300-e8b4-11ea-90a9-2d65e1555257.png)

As this shapefile contains lakes, and not land, I had to add a small modification to `reader_shape`, namely the possibility to add `invert=True` to switch between land and ocean/lake. Thus to use this feature, you should update to the latest version from GitHub.

**Comment by josefilho77** [comment]
Dear KnutFrode,

I am trying to use the reader_shape as well. 
It runs ok and I can add it following your code example, but there is some error on the axis. Could you help me on how to solve that and set axis limit only in my shape polygon?

I tried to use ax.set_xlim, ylim, but it returns:

ValueError: Image size of -958797335x790800990 pixels is too large. It must be less than 2^16 in each direction.

<Figure size 792x401.286 with 1 Axes>


![Figure_1](https://user-images.githubusercontent.com/59928324/91892318-d145fc00-ec68-11ea-9e2e-7a6572ffcfd6.png)

Best regards,

**Comment by knutfrode** [comment]
You may try to provide `corners=[lonmin, lonmax, latmin, latmax]` to the plot-command.

Alternatively, you can try `ax.set_extent([lonmin, lonmax, latmin, latmax], crs=ccrs.PlateCarree())` afterwards, as is done internally:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/basemodel.py#L2566

**Comment by josefilho77** [comment]
The "Corners" solution worked fine for o.plot(). Thank you!

Could I ask what would be the workaround to do the same for o.animation() and save it?
 
I tried to do the same, adding geometries to the axis, but it does not work. 
I set hide_landmask=True, but the geometries did not show up.

Best

**Comment by josefilho77** [comment]
Hi again,

I am able to plot my own land_binary_mask as a shapefile object, using o.plot (), as you can see on:

![image](https://user-images.githubusercontent.com/59928324/93216479-29d3c980-f73e-11ea-9f3b-d0615d57f54e.png)

_ax,_=o.plot(hide_landmask=True, show=False,
             corners=[xmin,xmax, ymin, ymax])

ax.add_geometries(reader_lake.polys,
                  ccrs.PlateCarree(),
                  facecolor=cfeature.COLORS['land'],
                  edgecolor='black')_

Nonetheless, when I try to use:

_o.animation(hide_landmask=True, show_trajectories=True,
            filename='3D.gif',
            corners=[xmin,xmax, ymin, ymax])

plt.show()_

It returns a gif without landmask, as you can see on the next figure:
![image](https://user-images.githubusercontent.com/59928324/93216989-ca29ee00-f73e-11ea-8d24-86d83396e951.png)

What am I missing? I am not an expert in python so maybe it is a syntax error.

Thanks in advance,

Jose

**Comment by knutfrode** [comment]
It was not possible until now to show a custom landmask from shapefile on animations, only with `plot()`

But if you update to the latest version (`git pull`) the custom landmask will be shown by default:
https://github.com/OpenDrift/opendrift/blob/master/examples/example_shape_landmask.py

**Comment by josefilho77** [comment]
Thats great news.

Thank you very much.

I updated it using git pull and tried to run my model again, but now it is returning me this error for both using "general:use_auto_landmask:True/False". 

12:24:30 DEBUG: No elements to deactivate
12:24:30 DEBUG: Calling OceanDrift.update()
12:24:30 WARNING: The simulation stopped before requested end time was reached.
12:24:30 INFO: ========================
12:24:30 INFO: End of simulation:
12:24:30 INFO: 'PassiveTracer' object has no attribute 'moving'
12:24:30 INFO: Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\opendrift\models\basemodel.py", line 2302, in run
    self.update()
  File "C:\ProgramData\Anaconda3\lib\site-packages\opendrift\models\oceandrift.py", line 55, in update
    self.advect_ocean_current()
  File "C:\ProgramData\Anaconda3\lib\site-packages\opendrift\models\physics_methods.py", line 343, in advect_ocean_current
    factor*self.environment.y_sea_water_velocity)
  File "C:\ProgramData\Anaconda3\lib\site-packages\opendrift\models\basemodel.py", line 3733, in update_positions
    velocity = velocity * self.elements.moving  # Do not move frosen elements
AttributeError: 'PassiveTracer' object has no attribute 'moving'

12:24:30 INFO: 'The simulation stopped before requested end time was reached.'

12:24:30 INFO: ========================
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\opendrift\models\basemodel.py in run(self, time_step, steps, time_step_output, duration, end_time, outfile, export_variables, export_buffer_length, stop_on_error)
   2301                     self.timer_start('main loop:updating elements')
-> 2302                     self.update()
   2303                     self.timer_end('main loop:updating elements')

C:\ProgramData\Anaconda3\lib\site-packages\opendrift\models\oceandrift.py in update(self)
     54         # Simply move particles with ambient current
---> 55         self.advect_ocean_current()
     56 

C:\ProgramData\Anaconda3\lib\site-packages\opendrift\models\physics_methods.py in advect_ocean_current(self, factor)
    342                     factor*self.environment.x_sea_water_velocity,
--> 343                     factor*self.environment.y_sea_water_velocity)
    344         else:

C:\ProgramData\Anaconda3\lib\site-packages\opendrift\models\basemodel.py in update_positions(self, x_vel, y_vel)
   3732         velocity = np.sqrt(x_vel**2 + y_vel**2)  # Velocity in m/s
-> 3733         velocity = velocity * self.elements.moving  # Do not move frosen elements
   3734 

AttributeError: 'PassiveTracer' object has no attribute 'moving'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-6-f4fe999f32ae> in <module>
      8 o.run(end_time = reader_current.end_time,
      9       time_step=timedelta(minutes=60),
---> 10       time_step_output=timedelta(minutes=60))

C:\ProgramData\Anaconda3\lib\site-packages\opendrift\models\basemodel.py in run(self, time_step, steps, time_step_output, duration, end_time, outfile, export_variables, export_buffer_length, stop_on_error)
   2335                 if self.steps_calculation <= 1:
   2336                     raise ValueError('Simulation stopped within '
-> 2337                         'first timestep. ' + self.get_messages())
   2338                 break
   2339 

ValueError: Simulation stopped within first timestep. 'The simulation stopped before requested end time was reached.'

Do you have any idea?

**Comment by knutfrode** [comment]
I wonder if these paths indicate that you installed OpenDrift using `conda install <...>` ?
If so, you might need to also follow the additional steps here (Alternative 1: already installed):
https://opendrift.github.io/install.html#alternative-1-already-installed

If this does not help, could you please check that the testall-script completes without errors?
If this is ok, you may post your complete code example, and I will try to reproduce the errors above.

**Comment by josefilho77** [comment]
Yes, you are correct. There was some issue with my old opendrift environment path, so I've removed it.
After that, I followed the instructions from "alternative 1" and installed a fresh-editable and updated opendrift environment.

Now the model runs ok, if I set _'general:use_auto_landmask', True.
However, when I set the opposite (auto_landmask,False), my particles starts outside of the domain for no reason... I thought It could be something related to my shapefile, but I was using it before the update along with 'corners' properties. and it was ok.

**My code:**
_o = OceanDrift(loglevel=0)  # Basic drift model suitable for passive tracers or drifters
#######################
# Preparing Readers
#######################
reader_current = reader_netCDF_CF_generic.Reader('D:\\TEL_Results\\pe_15dias.nc')
reader_shp = reader_shape.Reader.from_shpfiles('D:\\TEL_Results\\Land_binary_mask_pjct.shp')
#######################
# Seeding elements
#######################
lons = np.linspace(-34.769274, -34.730446, 5)
lats = np.linspace(-7.850100, -7.814750, 5)
lons, lats = np.meshgrid(lons, lats)
lon = lons.ravel()
lat = lats.ravel()
o.seed_elements(lon=lon, lat=lat,
                number=5*5, radius=0, cone=False,
                time=datetime(2013,7,16))
               # wind_drift_factor=wind_drift_factor)
#######################
# Running model
#######################
o.add_reader([reader_current,reader_shp])
o.set_config('general:use_auto_landmask', False)
o.set_config('general:coastline_action', 'stranding')
o.run(end_time = reader_current.end_time,
      time_step=timedelta(minutes=60),
      time_step_output=timedelta(minutes=60))
###########################
# Print and plot results
###########################
print(o)

o.plot()
o.animation()_

**The error:**

10:11:23 DEBUG: Calculation SRS set to: None
10:11:23 INFO: OpenDriftSimulation initialised (version 1.3.2)
10:11:23 INFO: Opening dataset: D:\TEL_Results\pe_15dias.nc
10:11:23 INFO: Opening file with Dataset
10:11:23 DEBUG: Finding coordinate variables.
10:11:23 DEBUG: Parsing variable: time
10:11:23 DEBUG: Parsing variable: longitude
10:11:23 DEBUG: Parsing variable: latitude
10:11:23 DEBUG: Parsing variable: sea_floor_depth_below_sea_level
10:11:23 DEBUG: Parsing variable: x_sea_water_velocity
10:11:23 DEBUG: Parsing variable: y_sea_water_velocity
10:11:23 DEBUG: Lon and lat are 1D arrays, assuming latong projection
10:11:23 DEBUG: Setting buffer size 465 for reader D:\TEL_Results\pe_15dias.nc, assuming a maximum average speed of 5 m/s.
10:11:23 DEBUG: Reading shapefile: D:\TEL_Results\Land_binary_mask_pjct.shp
10:11:23 INFO: Pre-processing 7 geometries
10:11:23 DEBUG: Setting buffer size 95 for reader D:\TEL_Results\pe_15dias.nc, assuming a maximum average speed of 1 m/s.
10:11:23 DEBUG: Calculation SRS set to: +proj=longlat +ellps=WGS84 +no_defs
10:11:23 DEBUG: Using srs for common grid: +proj=latlong
10:11:23 DEBUG: Added reader D:\TEL_Results\pe_15dias.nc
10:11:23 DEBUG: Added reader shape
10:11:23 DEBUG: 
------------------------------------------------------
Software and hardware:
  OpenDrift version 1.3.2
  Platform: Windows, 10
  7.889362335205078 GB memory
  4 processors (Intel64 Family 6 Model 142 Stepping 9, GenuineIntel)
  NumPy version 1.19.1
  SciPy version 1.5.0
  Matplotlib version 3.3.2
  NetCDF4 version 1.5.4
  Python version 3.8.5 | packaged by conda-forge | (default, Sep 16 2020, 17:19:16) [MSC v.1916 64 bit (AMD64)]
------------------------------------------------------

10:11:23 INFO: Config validation OK
10:11:23 DEBUG: No output file is specified, neglecting export_buffer_length
10:11:23 INFO: Fallback values will be used for the following variables which have no readers: 
10:11:23 INFO: 	x_wind: 0.000000
10:11:23 INFO: 	y_wind: 0.000000
10:11:23 INFO: 	upward_sea_water_velocity: 0.000000
10:11:23 INFO: 	ocean_vertical_diffusivity: 0.020000
10:11:23 INFO: 	sea_surface_wave_significant_height: 0.000000
10:11:23 INFO: 	sea_surface_wave_stokes_drift_x_velocity: 0.000000
10:11:23 INFO: 	sea_surface_wave_stokes_drift_y_velocity: 0.000000
10:11:23 INFO: 	sea_surface_wave_period_at_variance_spectral_density_maximum: 0.000000
10:11:23 INFO: 	sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment: 0.000000
10:11:23 INFO: 	surface_downward_x_stress: 0.000000
10:11:23 INFO: 	surface_downward_y_stress: 0.000000
10:11:23 INFO: 	turbulent_kinetic_energy: 0.000000
10:11:23 INFO: 	turbulent_generic_length_scale: 0.000000
10:11:23 DEBUG: Preparing readers for simulation coverage ([-46.5549010927551, -19.52577571611147, -22.944820434344507, 3.860925481126115]) and time (2013-07-16 00:00:00 to 2013-07-31 00:00:00)
10:11:23 DEBUG: 	Preparing D:\TEL_Results\pe_15dias.nc
10:11:23 DEBUG: 	Preparing shape
10:11:23 INFO: Using existing reader for land_binary_mask
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Variable group ['land_binary_mask']
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Calling reader shape
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Data needed for 25 elements
10:11:23 INFO: ========================
10:11:23 INFO: Exception:
10:11:23 INFO: All 25 particles (-34.77--34.73E, -7.85--7.81N) are outside domain of shape (-35.10--34.81E, -8.22--7.58N)
10:11:23 DEBUG: Traceback (most recent call last):
  File "d:\opendrift\opendrift\models\basemodel.py", line 977, in get_environment
    reader.get_variables_interpolated(
  File "d:\opendrift\opendrift\readers\basereader.py", line 475, in get_variables_interpolated
    raise ValueError(('All %s particles (%.2f-%.2fE, %.2f-%.2fN) ' +
ValueError: All 25 particles (-34.77--34.73E, -7.85--7.81N) are outside domain of shape (-35.10--34.81E, -8.22--7.58N)

10:11:23 INFO: ========================
10:11:23 DEBUG: ---------------------------------------
10:11:23 DEBUG: Finished processing all variable groups
10:11:23 DEBUG: ------------ SUMMARY -------------
10:11:23 DEBUG:     land_binary_mask: nan (min) nan (max)
10:11:23 DEBUG: ---------------------------------
10:11:23 DEBUG: 		0 active elements
10:11:23 INFO: Moving 0 out of 25 points from land to water
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Variable group ['land_binary_mask']
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Calling reader shape
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Data needed for 168 elements
10:11:23 DEBUG: Reader time:
		None (before)
		None (after)
10:11:23 DEBUG: Fetching variables from shape
10:11:23 DEBUG: Fetched env-before
10:11:23 DEBUG: No time interpolation needed - right on time.
10:11:23 DEBUG: Reader SRS is the same as calculation SRS - rotation of vectors is not needed.
10:11:23 DEBUG: Obtained data for all elements.
10:11:23 DEBUG: ---------------------------------------
10:11:23 DEBUG: Finished processing all variable groups
10:11:23 DEBUG: ------------ SUMMARY -------------
10:11:23 DEBUG:     land_binary_mask: 0 (min) 0 (max)
10:11:23 DEBUG: ---------------------------------
10:11:23 DEBUG: 		0 active elements
10:11:23 DEBUG: to be seeded: 25, already seeded 0
10:11:23 DEBUG: Released 25 new elements.
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Variable group ['sea_floor_depth_below_sea_level']
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Calling reader D:\TEL_Results\pe_15dias.nc
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Data needed for 25 elements
10:11:23 DEBUG: Reader time:
		2013-07-16 00:00:00 (before)
		2013-07-16 00:29:59.972534 (after)
10:11:23 DEBUG: Fetching variables from D:\TEL_Results\pe_15dias.nc
10:11:23 DEBUG: Fetched env-block (size 411x397x1) for time before (2013-07-16 00:00:00)
10:11:23 DEBUG: Interpolating before (2013-07-16 00:00:00) in space  (linearNDFast)
10:11:23 DEBUG: Initialising interpolator.
10:11:23 DEBUG: No time interpolation needed - right on time.
10:11:23 DEBUG: Obtained data for all elements.
10:11:23 DEBUG: ---------------------------------------
10:11:23 DEBUG: Finished processing all variable groups
10:11:23 DEBUG: ------------ SUMMARY -------------
10:11:23 DEBUG:     sea_floor_depth_below_sea_level: -25.2761 (min) -16.9851 (max)
10:11:23 DEBUG: ---------------------------------
10:11:23 DEBUG: 		25 active elements
10:11:23 DEBUG: 		-7.8501 <- latitude  -> -7.81475
10:11:23 DEBUG: 		-34.769276 <- longitude -> -34.730446
10:11:23 DEBUG: 		z = 0.0
10:11:23 DEBUG: ---------------------------------
10:11:23 DEBUG: ======================================================================
10:11:23 INFO: 2013-07-16 00:00:00 - step 1 of 360 - 25 active elements (0 deactivated)
10:11:23 DEBUG: 0 elements scheduled.
10:11:23 DEBUG: ======================================================================
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Variable group ['sea_floor_depth_below_sea_level', 'x_sea_water_velocity', 'y_sea_water_velocity']
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Calling reader D:\TEL_Results\pe_15dias.nc
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Data needed for 25 elements
10:11:23 DEBUG: Reader time:
		2013-07-16 00:00:00 (before)
		2013-07-16 00:29:59.972534 (after)
10:11:23 DEBUG: Fetching variables from D:\TEL_Results\pe_15dias.nc
10:11:23 DEBUG: Fetched env-block (size 411x397x1) for time before (2013-07-16 00:00:00)
10:11:23 DEBUG: Interpolating before (2013-07-16 00:00:00) in space  (linearNDFast)
10:11:23 DEBUG: Initialising interpolator.
10:11:23 DEBUG: No time interpolation needed - right on time.
10:11:23 DEBUG: Rotating vectors between 0.0 and 0.0 degrees.
10:11:23 DEBUG: Obtained data for all elements.
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Variable group ['land_binary_mask']
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Calling reader shape
10:11:23 DEBUG: ----------------------------------------
10:11:23 DEBUG: Data needed for 25 elements
10:11:23 INFO: ========================
10:11:23 INFO: Exception:
10:11:23 INFO: All 25 particles (-34.77--34.73E, -7.85--7.81N) are outside domain of shape (-35.10--34.81E, -8.22--7.58N)
10:11:23 DEBUG: Traceback (most recent call last):
  File "d:\opendrift\opendrift\models\basemodel.py", line 977, in get_environment
    reader.get_variables_interpolated(
  File "d:\opendrift\opendrift\readers\basereader.py", line 475, in get_variables_interpolated
    raise ValueError(('All %s particles (%.2f-%.2fE, %.2f-%.2fN) ' +
ValueError: All 25 particles (-34.77--34.73E, -7.85--7.81N) are outside domain of shape (-35.10--34.81E, -8.22--7.58N)

10:11:23 INFO: ========================
10:11:23 DEBUG: ---------------------------------------
10:11:23 DEBUG: Finished processing all variable groups
10:11:23 DEBUG: Creating empty dictionary for profiles not profided by any reader: ['ocean_vertical_diffusivity']
10:11:23 DEBUG:       Using fallback value 0.02 for ocean_vertical_diffusivity for all profiles
10:11:23 DEBUG: ------------ SUMMARY -------------
10:11:23 DEBUG:     x_sea_water_velocity: 5.64578e-05 (min) 0.00624297 (max)
10:11:23 DEBUG:     y_sea_water_velocity: -0.00350953 (min) 0.00961141 (max)
10:11:23 DEBUG:     x_wind: 0 (min) 0 (max)
10:11:23 DEBUG:     y_wind: 0 (min) 0 (max)
10:11:23 DEBUG:     upward_sea_water_velocity: 0 (min) 0 (max)
10:11:23 DEBUG:     ocean_vertical_diffusivity: 0.02 (min) 0.02 (max)
10:11:23 DEBUG:     sea_surface_wave_significant_height: 0 (min) 0 (max)
10:11:23 DEBUG:     sea_surface_wave_stokes_drift_x_velocity: 0 (min) 0 (max)
10:11:23 DEBUG:     sea_surface_wave_stokes_drift_y_velocity: 0 (min) 0 (max)
10:11:23 DEBUG:     sea_surface_wave_period_at_variance_spectral_density_maximum: 0 (min) 0 (max)
10:11:23 DEBUG:     sea_surface_wave_mean_period_from_variance_spectral_density_second_frequency_moment: 0 (min) 0 (max)
10:11:23 DEBUG:     surface_downward_x_stress: 0 (min) 0 (max)
10:11:23 DEBUG:     surface_downward_y_stress: 0 (min) 0 (max)
10:11:23 DEBUG:     turbulent_kinetic_energy: 0 (min) 0 (max)
10:11:23 DEBUG:     turbulent_generic_length_scale: 0 (min) 0 (max)
10:11:23 DEBUG:     sea_floor_depth_below_sea_level: -25.2761 (min) -16.9851 (max)
10:11:23 DEBUG:     land_binary_mask: nan (min) nan (max)
10:11:23 DEBUG: ---------------------------------
10:11:23 DEBUG: 		25 active elements
10:11:23 DEBUG: 		-7.8501 <- latitude  -> -7.81475
10:11:23 DEBUG: 		-34.769276 <- longitude -> -34.730446
10:11:23 DEBUG: 		16.985065460205078   <- z ->   25.276147842407227
10:11:23 DEBUG: ---------------------------------
10:11:23 DEBUG: Calculating Hs from wind, min: 0.000000, mean: 0.000000, max: 0.000000
10:11:23 DEBUG: Calculating wave period Tm02 from wind
10:11:23 DEBUG:    min: 1.256637, mean: 1.256637, max: 1.256637
10:11:23 DEBUG: Calculating wave period from wind, min: 1.256637, mean: 1.256637, max: 1.256637
10:11:23 WARNING: Missing variables: ['land_binary_mask']
10:11:23 DEBUG: Added status missing_data
10:11:23 DEBUG: 25 elements scheduled for deactivation (missing_data)
10:11:23 DEBUG: 	(z: 16.985065 to 25.276148)
10:11:23 DEBUG: Removed 25 elements.
10:11:23 DEBUG: Removed 25 values from environment.
10:11:23 DEBUG: remove items from profile for z
10:11:23 DEBUG: remove items from profile for ocean_vertical_diffusivity
10:11:23 DEBUG: Removed 25 values from environment_profiles.
10:11:23 WARNING: The simulation stopped before requested end time was reached.
10:11:23 INFO: ========================
10:11:23 INFO: End of simulation:
10:11:23 INFO: No more active or scheduled elements, quitting.
10:11:23 INFO: Traceback (most recent call last):
  File "d:\opendrift\opendrift\models\basemodel.py", line 2320, in run
    raise ValueError('No more active or scheduled elements, quitting.')
ValueError: No more active or scheduled elements, quitting.

10:11:23 INFO: "Missing variables: ['land_binary_mask']", 'The simulation stopped before requested end time was reached.'

10:11:23 INFO: ========================
Traceback (most recent call last):

  File "d:\opendrift\opendrift\models\basemodel.py", line 2320, in run
    raise ValueError('No more active or scheduled elements, quitting.')

ValueError: No more active or scheduled elements, quitting.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\JoseFilho\Desktop\example_drifter_PE.py", line 42, in <module>
    o.run(end_time = reader_current.end_time,

  File "d:\opendrift\opendrift\models\basemodel.py", line 2364, in run
    raise ValueError('Simulation stopped within '

ValueError: Simulation stopped within first timestep. "Missing variables: ['land_binary_mask']", 'The simulation stopped before requested end time was reached.'



I am sorry for flooding the topic with sentences. I am afraid I can't send my netcdf files because it has 41Gb.
[land_binary_mask.zip](https://github.com/OpenDrift/opendrift/files/5239326/land_binary_mask.zip)

Best regards

**Comment by knutfrode** [comment]
Yes, this was a bit strange. Or actually it is strange that it worked before, with particles outside the coverage of your landmask.

But perhaps it works if you add:
```
o.fallback_values['land_binary_mask'] = 0
```
This means that there is assumed to be ocean outside of your landmask coverage.

**Comment by josefilho77** [comment]
Yes, it works nicely now. Thank you very much again. 

Best
