### ISSUE TITLE
why did elements move in leeway when I set the x_sea_water_velocity, y_sea_water_velocity, x_wind and y_wind to zero?

### ISSUE THREAD

**Issue by limaolin1981611** [OpenDrift/opendrift#397]
I set x_sea_water_velocity, y_sea_water_velocity, x_wind and y_wind as follows:
    lw.fallback_values['x_sea_water_velocity']=0
    lw.fallback_values['y_sea_water_velocity']=0
    lw.fallback_values['x_wind']=0
    lw.fallback_values['y_wind']=0
why did elements move?

**Comment by limaolin1981611** [comment]
![leeway_point_run](https://user-images.githubusercontent.com/62914884/95679853-0ea68d80-0c08-11eb-8695-54f3718e42a3.jpg)

**Comment by knutfrode** [comment]
This is because Leeway is an empirical model, where coefficients include standard deviations in addition to the mean values.
So even if current is 0, this is in the model interpreted as a mean value, and some perturbations are added (in all directions) to mimic the uncertainty.

Other modules (e.g. OceanDrift) do not do this, unless you provided a horizontal diffusivity:
```
o.set_config('drift:horizontal_diffusivity', <some value>)
```

**Comment by knutfrode** [comment]
Closing this issue. Please re-open if still relevant.
