### ISSUE TITLE
The trajectories of different objects are not same under the same water_uv?

### ISSUE THREAD

**Issue by limaolin1981611** [OpenDrift/opendrift#471]
I have set the parameters as follows:  objectType to 26 and 16, x_wind and y_wind both to 0, reader_water_uv both from norkyst800_subset_16Nov2015.nc. I thought the results were same, but they were different. Why?

![leeway_point_run1](https://user-images.githubusercontent.com/62914884/102042541-0b4c9f80-3e0d-11eb-83a4-1e0ce8b47bfc.jpg)

![leeway_point_run2](https://user-images.githubusercontent.com/62914884/102042558-17386180-3e0d-11eb-8e65-d4f328fdaddf.jpg)

**Comment by limaolin1981611** [comment]
![leeway_point_run1](https://user-images.githubusercontent.com/62914884/102042254-574b1480-3e0c-11eb-8a3f-35dffc1f984f.png)

**Comment by limaolin1981611** [comment]
![leeway_point_run1](https://user-images.githubusercontent.com/62914884/102042411-c1fc5000-3e0c-11eb-8973-dadc9a8610b9.jpg)
![leeway_point_run2](https://user-images.githubusercontent.com/62914884/102042415-c3c61380-3e0c-11eb-9896-e6821b8d882b.jpg)

**Comment by limaolin1981611** [comment]
![leeway_point_run1](https://user-images.githubusercontent.com/62914884/102042457-d8a2a700-3e0c-11eb-8190-630d0fc0c32a.jpg)

**Comment by knutfrode** [comment]
This is because the Leeway model contains coefficients with both mean and perturbations/standard-deviations to the windage. to include variability/uncertainty. So even with zero wind, the model add some perturbations.

This is the same reason as discussed in #397

**Comment by limaolin1981611** [comment]
OK, Thanks

**Comment by limaolin1981611** [comment]
If I only want to  take wate_uv into account, How ? I have set the 3rd, 6th and 9th parameters of drift properties of an object to 0, It not works.

**Comment by knutfrode** [comment]
I believe you will get only current if you choose category "SLDMB".

However, for this case you should rather use OceanDrift instead of Leeway
model.

**Comment by limaolin1981611** [comment]
Can you tell me the differences and relationships among leeway, oceandrift and shipdrift? And how can I choose the right model from them?

**Comment by knutfrode** [comment]
Leeway is for objects floating at the surface, of any of the following categories:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/OBJECTPROP.DAT
This includes various types of ships and boats, up to length of about 30m.

TheShipDrift model is not based on categories, but on four adjustable parameters, the length, width and height (below and above water) of the ship. This should be used for ships larger than about 30m

The OceanDrift model is a general 3D model where particles can also move vertically due to vertical current component (if provided by a reader) or vertical mixing (if vertical diffusivity is larger than zero). But this may also be used as a 2D model (zero vertical velocity and mixing), where a "wind_drift_factor" may be specified to move objects with wind in addition to surface current.

**Comment by knutfrode** [comment]
Closing this issue. Please re-open if still relevant.
