### ISSUE TITLE
GDal issue on Windows giving errors when trying to run

### ISSUE THREAD

**Issue by rlr8b4** [OpenDrift/opendrift#53]
I'm trying to run open drift but I'm receiving this GDal error. I was not able  install it as suggested on my Windows PC and need help. Can you help?

**Comment by knutfrode** [comment]
I believe you forgot to paste the error message?

The easiest would be to install GDAL and everything else with Anaconda. But as noted on the [installation page](https://github.com/OpenDrift/opendrift/wiki), there is an issue with the latest version. The solution for that issue is to set the environment variable ```GDAL_DATA``` equal to the folder given by ```$gdal-config --datadir```

Also, GDAL is used only for some things, are you sure it is needed for your purpose?

**Comment by joeelrahi** [comment]
Hello,
I have the same error while installing "conda_python2.yml". I did set the environment variable GDAL_DATA to the folder but still doesn't work. Could you help ?

**Comment by knutfrode** [comment]
Hi,

Did you remember to activate this conda environment?
It would otherwise help if you could post some more of the error message that you receive.
Also the version numbers of GDAL would be useful to know.

**Comment by joeelrahi** [comment]
Hello Knut,

Thanks for your reply! Please find attached the error messages I’m getting. My GDAL version is gdal 2.2.2

Last, would you advise me to switch to Linux machine? Would this save me some trouble

With kind regards,
Joe




[cid:image001.png@01D4EE39.29615C20]

**Comment by knutfrode** [comment]
No, Windows should be fine.
I don't see your error message, though. Could you please paste it into the GitHub window, instead of as attachment to mail? Or as plain text in an email eply.
Most probably you will not need the GDAL functionality anyway, so you might also try to remove ```gdal``` and ```libgdal``` from the conda-config-file before installing it.

**Comment by joeelrahi** [comment]
Hello again,

I switched to Ubuntu and everything seems to be running smoother! I would like to thank you again for your continuous support and I would be more than grateful to share with you the results I am keen to obtain.

With kind regards,
Joe
