### ISSUE TITLE
Meaning of Warning: Buffer size

### ISSUE THREAD

**Issue by AndresSepulveda** [OpenDrift/opendrift#569]
What is the meaning of ths warning? Is it relevant to the calculation speed?
 
 WARNING opendrift.readers.basereader.structured: Data block from roms native not large enough to cover element positions within timestep. Buffer size (82) must be increased.

**Comment by gauteh** [comment]
It means that the particles are moving faster than what is anticipated. Data is fetched in blocks, so that reads do not have to be done on every time step, this usually makes things much faster. You can increase it with `set_buffer_size` on the reader (https://opendrift.github.io/autoapi/opendrift/readers/basereader/variables/index.html?highlight=set_buffer#opendrift.readers.basereader.variables.Variables.set_buffer_size)

**Comment by knutfrode** [comment]
I also found out that this often happen when seeding over an area and over time (e.g. along a transect), since particles may be seeded outside of the hitherto-read-data-blocks. This is not critical, as it only means that one-sided-interpolation will be performed in time for this time step for the actual elements.
The warning is anyway a bit annoying, so we would like to fix this and remove it. But as long as the issue is not solved, it is better to have this reminder so that it is not forgotten.
