### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('setuptools-scm')

### ISSUE THREAD

**Issue by dungnm345** [OpenDrift/opendrift#58]
Hello,
I am installing OpenDrift with the command "python setup.py develop --user", and it shows the error:
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm')

I don't know how to fix it, thanks for any help.

**Comment by knutfrode** [comment]
Hi,

It is always a good idea to search on Google for the error message, which
in this case gives e.g.:
https://www.bountysource.com/issues/35571284-setuptools_scm-could-not-be-found

So probably your problem may be solved by:
pip install setuptools_scm





2017-11-13 8:45 GMT+01:00 dungnm345 <notifications@github.com>:

**Comment by dungnm345** [comment]
I had tried but unsuccessfully. It shows the error below. To be honest, i am very new to Ubuntu.

/usr/bin/pip:5: UserWarning: Module dap was already imported from None, but /usr/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import load_entry_point
Downloading/unpacking setuptools-scm
  Cannot fetch index base URL http://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement setuptools-scm
No distributions at all found for setuptools-scm
Storing complete log in /home/dung/.pip/pip.log

**Comment by knutfrode** [comment]
There seems to be an issue with your internet connection, perhaps related to a proxy?
https://stackoverflow.com/questions/21294997/pip-connection-failure-cannot-fetch-index-base-url-http-pypi-python-org-simpl
https://stackoverflow.com/questions/15501133/python-pip-error-cannot-fetch-index-base-url-https-pypi-python-org-simple
https://github.com/pypa/pip/issues/478

If you don't find a solution on those pages, perhaps could could try to post a question on e.g. stackoverflow: https://stackoverflow.com/
Your issue is in fact about ubuntu/installing, and not directly related to OpenDrift.

Alternatively, you might want to try instead to use Anaconda (miniconda) to install OpenDrift and its requirements, as mentioned here: https://github.com/opendrift/opendrift/wiki#download-and-installation

**Comment by daniel951127** [comment]
a mi me da el siguien error 
could not find suitable distribution for requirement.parse(tornado==4.5.3)

**Comment by knutfrode** [comment]
Please reopen if you still face this problem.

**Comment by ZeeshanMirza74** [comment]
i am facing this error when i run this code https://github.com/hanzhichao2000/pysentiment
, kindly tell me what should I do


usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by gauteh** [comment]
See here for how to install opendrift: https://opendrift.github.io/install.html
