### ISSUE TITLE
Running example codegg with Telemac 3D currents field

### ISSUE THREAD

**Issue by taoansf** [OpenDrift/opendrift#60]
Hello,

I'm trying to run the example codegg using a NETCDF file created from Telemac 3d currents data. The simulation is running until the end,  without show any error, but the currents field are not working.

I think it could be some wrong NETCDF parameter on my netcdf file, but I don't know how tho check this, because the model is running without error message.

I will be grateful if you can test my simulation files to help me find the solution

[correntes.zip](https://github.com/OpenDrift/opendrift/files/1535980/correntes.zip)

[example_codegg_TELEMAC.zip](https://github.com/OpenDrift/opendrift/files/1535977/example_codegg_TELEMAC.zip)

With best regards,

Taoan

**Comment by knutfrode** [comment]
Hi,

This netCDF file does not contain gridded data, but unstructured data. The OpenDrift netCDF reader can currently not read such files, but this is planned for the (distant) future.
Are you able to transform the data to a regular grid?

**Comment by taoansf** [comment]
Hello,
Follwing your sugestion, I formated a grided version of netCDF file, but it is not working.
Do you have any idea what could be wrong?

[opendrift_telemac.zip](https://github.com/OpenDrift/opendrift/files/1540253/opendrift_telemac.zip)

With best regards,

Taoan

**Comment by taoansf** [comment]
Sorry for wrong files on my last post
This is the correct structured file
[opendrift_telemacV2.zip](https://github.com/OpenDrift/opendrift/files/1540718/opendrift_telemacV2.zip)

**Comment by knutfrode** [comment]
There are still some issues with this file:
- there is a dimension ```planos``` which is not supported/understood by OpenDrift, dimension order must be: ```(time, y, x)``` or ```(time, depth, y, x)```, according to CF conventions. If ```planos``` would be a depth dimension, then it must also be a 1D variable, but in this case 'depth' is in fact a 4D variable 
- ```standard_name``` is misspelled as ```standart_name``` for the gridded variables

To use the netCDF_CF_generic reader, the file must comply strictly to the [CF conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html).
The CF-convention is quite picky on things like ```standard_name```.

Please also update your OpenDrift to the latest version, as I just commited a minor update to support 1D lon and lat coordinates, so that your file should be readable if you manage to make it comply with the CF convention.

**Comment by taoansf** [comment]
Hello,
I applied your sugestions and it is working now!
[opendrift_telemacV3.zip](https://github.com/OpenDrift/opendrift/files/1542886/opendrift_telemacV3.zip)

However, after update opendrift to the latest version the plots are not being shown.
I noted the follwowing message when opendrift start simulation _"No display found. Using non-interactive Agg backend"_ see image below.

![no_display](https://user-images.githubusercontent.com/22460776/33769802-4d5c0144-dc0a-11e7-9f85-6814ca00b52e.JPG)

**Comment by knutfrode** [comment]
Good that it worked!

The missing plots are probably because the DISPLAY environment variable is
not set within your programming IDE.
Which IDE are you using? I cannot recognise it from the screenshot.
The following workaround was made for the PyCharm IDE a couple of weeks ago:
https://github.com/OpenDrift/opendrift/commit/4215aaf4c45847d76f8337da8233bafeacb7f75b

2017-12-08 15:28 GMT+01:00 taoansf <notifications@github.com>:

**Comment by taoansf** [comment]
Hello,

I'm working with default Python IDLE version 2.7.5 with Windows 10
![python](https://user-images.githubusercontent.com/22460776/33772745-78495fdc-dc14-11e7-9e1f-28d26060752a.JPG)

**Comment by arianjoel93** [comment]
How can I write the transformed data from an unstructured grid to the regular grid in a netCDF file?
Thank You

**Comment by taoansf** [comment]
> How can I write the transformed data from an unstructured grid to the regular grid in a netCDF file?
> Thank You

Hello,
In my case, I wrote a regular netCDF file from Telemac3D result file using a python script. If you have some skill with python you can do it using python netCDF4 module https://github.com/Unidata/netcdf4-python

I don't know what hydrodynamic model you are using, but if you are using Telemac you can adapt my python script for your case.


[tel2opendrift_netcdf_3d_V4.zip](https://github.com/OpenDrift/opendrift/files/3217131/tel2opendrift_netcdf_3d_V4.zip)

With best regards,

Taoan

**Comment by arianjoel93** [comment]
Thank you for your answers.
I already interpolated the data to a regular grid. I just have to configure the netCDF file
I use the ADCIRC model. Then I will adapt your python scritps of Taoan for my case. 
I have used reader_netCDF_CF_unstructured.py, but my netCDF file is missing some attributes because the required variables do not take the values ​​from my netCDF file

Very grateful for your answers.

thank you
Joel
