### ISSUE TITLE
Using a land mask from shapefile

### ISSUE THREAD

**Issue by taoansf** [OpenDrift/opendrift#61]
Hello,

I would like to know if there is some method to use a land mask from a shapefile or another file type in opendrift simulations.

I have a shapefile with better resolution to my study area than that from Base Map data, and I would like to use it.
If you have some idea, please share with me.

With best regards,

Taoan

**Comment by knutfrode** [comment]
OpenDrift is modular also with respect to landmask. Thus the landmask (CF standard_name: ```land_binary_mask```) may be provided by any reader. The default, and most common, if no dedicated reader for landmask has been added, is to revert to [reader_basemap_landmask](https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_basemap_landmask.py)

As with your shapefiles, this is also based on vector coastlines. Thus I would suggest that you could copy the basemap reader, and adapt it to work with your shapefiles instead. It works this way:
1. The reader is initialised by providing limits of longitude and latitude
2. All land contours/polygons from Basemap (GSHHS) covering this "box" are extracted/collected 
3. The ```get_variables```method checks which of the provided lon/lat positions are within any of the land polygons, and returns 1 for this case, 0 otherwise

To speed up (and complicate...) this process, a rasterisation of the domain is also done at time of initialisation, making a 2D raster map (typically 500m resolution). This is used for a first screening, so that particles which are within a "no land" pixel in this 2D map do not have to be checked against all the land polygons.

In making such a "shapefile-landmask-reader", it would be very nice if it could be generalised, so that it can work with any shapefile.

**Comment by taoansf** [comment]
Hello,
Considering your sugestions, so can I use reader_netCDF_CF_generic to read my "land_binary_mask" variable directly on my NetCDF file?

If true, I can convert myshapefile to a binary raster and write it on my NetCDF file. However, I think that could be problematic to lead with diferent grid resolutions on the same file. This is because my land mask grid has higher resolution than the water velocity grid. 
This manner, is it possible to read my land mask using a separated netcdf file?
Another question is...will opendrift plot results using my land_mask or using Basemap to draw coast lines?

I also think at the possibility to read shapefile directly using [mpl_toolkits.basemap of Matplotlib](http://basemaptutorial.readthedocs.io/en/latest/shapefile.html) as an alternative argument on reader_basemap_landmask. This manner, I can extract de polygon coordinates from shapefile and use it as input data.
I think a modification of code could be done here on reader_basemap_landmask:
# Extract polygons for faster checking of stranding
if has_nxutils is True:
            self.polygons = [p.boundary for p in self.map.landpolygons]
        else:
            self.polygons = [Path(p.boundary) for p in self.map.landpolygons]

However I need to know what the strucutre of polygons array to put here. What do you think about it?

Thank you very much for your help

With best regards,

Taoan

**Comment by knutfrode** [comment]
Yes, rasterisation to netCDF is one solution which might be ok for many purposes. You could then also write this to a separate file with higher resolution, if the resolution of the current data is not sufficient.

Adding a shapefile-argument to existing basemap-reader sounds like a good solution, reusing instead of duplicating too much code. ```landpolygons``` is a special Matplotlib sub-class, where coordinates (x, y, ) may be retrieved with the method ```get_coords```
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_basemap_landmask.py#L197
But you could then replace and generalise a bit more of the code of the Basemap reader (which would then not anymore be a pure Basemap reader).

Presently, all plotting methods of OpenDrift use Basemap polygons for the coastlines. But this could in principle also be generalised to use contours from shapefile. Again, code should preferrently be shared between the checking of land for the simulation and the plotting.
As the Basemap package is not supported long into the future, a migration to [Cartopy](http://scitools.org.uk/cartopy/) should be done at some time (with overlap).

**Comment by taoansf** [comment]
Hello,

I'm testing my binary landmask file with example_codegg, but it is not working. 
All my elements are released over land. It looks like opendrift is using basemap coastline as reference instead of my landmask file.
Is there some addtional configuration to force opendrift to use my landmask? or maybe some formatation adjust necessary on my landmask file?

[test_landmask.zip](https://github.com/OpenDrift/opendrift/files/1551544/test_landmask.zip)

Thank you for your help

**Comment by knutfrode** [comment]
The landmask file is fine, but misses the ```standard_name``` attribute, which is the key for automatic identifiation of variables according to the [CF-convention](http://cfconventions.org/Data/cf-standard-names/48/build/cf-standard-name-table.html).
After adding this attribute with the following command, it works fine:
```ncatted -a standard_name,land_binary_mask,a,c,'land_binary_mask' landmask.nc landmask2.nc```

**Comment by taoansf** [comment]
Yes! it is working now! 
I also had to correct the binary values, because they are inverted ;)
I'm testing to export the results in netcdf and perform the plots using QGIS due to layout flexibility. It is working fine.
In future, I pretend to create some automatic plots directly with matplolib.

Thank you very much for your attention.

With best regards,

Taoan

**Comment by knutfrode** [comment]
Ok, that sounds good.
Then I close this issue.
