### ISSUE TITLE
Resolution limits problem in land_binary_mask file

### ISSUE THREAD

**Issue by taoansf** [OpenDrift/opendrift#62]
Hello,

I noted that opendrift give me a error if my land_binary_mask has pixel value below 50m. See image:

![error_delta_x](https://user-images.githubusercontent.com/22460776/33960281-011a5bf0-e029-11e7-84df-b30b6a532ef1.JPG)

[test_resolution_landmask.zip](https://github.com/OpenDrift/opendrift/files/1556953/test_resolution_landmask.zip)

Do you have some sugestion to solve this limitation? my intention is to work with 10m pixel for better representation of coastlines.

With best regards,

Taoan

**Comment by knutfrode** [comment]
The netCDF reader is checking that x- and y-coordinate vectors are regular, i.e. that delta_x and delta_y are constant - but allowing for 1% deviation due to rounding errors.
In your case x,y are lon,lat, and thus for such small delta_x,delta_y the rounding errors may be relatively large.

I suggest that you can change the 0.01 to e.g. 0.05 (5%) in the reader (lines 153 and 157), to see if that helps:
https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_netCDF_CF_generic.py#L153

**Comment by taoansf** [comment]
Yes it is working!

Thank you very much

**Comment by knutfrode** [comment]
I updated now the threshold from 1% to 5% in the official version. So if you update your code, your local modification might not anymore be needed.

Another change is also that the following config setting is needed to use landmask from a model instead of Basemap (which is default):
```o.set_config('general:use_basemap_landmask', False)```

Note also the following options for how elements shall interact with coastline (whether from Basemap or another reader):
https://github.com/OpenDrift/opendrift/wiki/Interaction-with-coastline

**Comment by taoansf** [comment]
Yes, good news!
I will update my opendrift version.
Thank you!
