### ISSUE TITLE
How to set priority of nested grids at boundary transition

### ISSUE THREAD

**Issue by taoansf** [OpenDrift/opendrift#675]
Hello,

I'm running a case with two nested ROMS grids and have some doubts about how to set priority for transition area betweeen the two grids.

![image](https://user-images.githubusercontent.com/22460776/128765973-a3769c2c-bd3c-4d2a-b2b5-892a72322305.png)

Considering the high-priority for the small grid inside the bay I set the reader order with small grid first. However, I don't know if this is the best solution because some drifters are being retained at ocean boundary of the small grid. I think this problem is caused by the reader priority setup at small grid boundary region. I believe that if I set the priority to the large grid at boundary of small grid I can get a more seamless transition.

![image](https://user-images.githubusercontent.com/22460776/128765789-89d00fcb-3048-4053-9b32-ac7ef1b985c8.png)

Do you have some idea how I can improve this?

Thanks for any help.

With best regards,

Taoan

**Comment by knutfrode** [comment]
Hi,

The fine/internal model must here be prioritized first, otherwise it will never be used.
Unless the two models are output from a nested model system, it is natural that there might be discontinuities of currents at the boundary, so elements "escaping" the inner model might be "pushed back" immediately by the outer model if the current vectors are pointing towards the internal domain. Thus you might occasionally see an aggregation of particles along the interface, and at other times no particles there (if both models have currents pointing away from the boundary). I believe there is no good solution to this problem.

Knut-Frode

**Comment by taoansf** [comment]
Hello,
I found a solution for this problem, by setting the parameter _max_speed=10_ 
I think this manner its is possible to prevent velocity fields discontinuities due to inconsistent buffer calculation for different grids resolution near ocean boundary region
