### ISSUE TITLE
Docker container?

### ISSUE THREAD

**Issue by vsoch** [OpenDrift/opendrift#79]
hey opendrift! I was wondering if anyone has need / desire for a Docker container? I'm a software engineer at Stanford and one of our users could use it... I'm working on one and could do a PR, and wanted to bring it up for discussion here in case there are "best practices" for the install. So far I'm using the miniconda (python 2) image from continuumio, and installing the dependencies with conda. I'm going through the errors from testing now - the first was that basemap "Axes" was missing a function, and I resolved that by doing the suggestion here: https://github.com/matplotlib/basemap/issues/395#issuecomment-381407388

I still see an issue about a missing GDAL although I've installed gdal-bin and libgeos-dev. Here is the message

```bash
DEBUG: Rasterized size: [458, 1518]
DEBUG: backend agg version v2.2
DEBUG: Calculation SRS set to: None
INFO: OpenDriftSimulation initialised (version 1.0.3)
GDAL is not available:
libgeos-3.4.2.so: cannot open shared object file: No such file or directory
```
The issue I'm having now is:

```bash
======================================================================
FAIL: test_plot_animation (test_run.TestRun)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/opendrift/tests/test_run.py", line 645, in test_plot_animation
    assert os.path.exists('test_plot.mp4')
AssertionError

----------------------------------------------------------------------
Ran 74 tests in 68.225s

FAILED (failures=1, skipped=5)
```
I see that the png output successfully, but the animation (mp4) did not, and I'm guessing it might be related to a library or graphics in the container? Would you be able to help me parse through these last issues and then I could contribute the Dockerfile to the repo as a PR? Many thanks!

**Comment by vsoch** [comment]
Here is the container I'm working on:

https://github.com/researchapps/sherlock/blob/master/opendrift/Dockerfile
https://hub.docker.com/r/vanessa/opendrift/

If it's an issue with display, it should actually work seamlessly once it's a Singularity container. If it's a library, we have more debugging to do! :) I'm building / pushing now, and I'll pull down into a Singularity container to retry the tests.

**Comment by knutfrode** [comment]
Hi Vanessa,

I have done some updates to OpenDrift lately, and it is now both Python2 and Python3 compatible. 
Could you please merge these updates into your fork, to see if tests are passing now?

There were a lot of trouble with tests seemingly randomly failing on Travis, but in the end it turned out to be a [problem with conda](https://github.com/conda/conda/issues/7341).

I am not familiar with Docker, but am happy to include a Dockerfile in the repository if it can be useful to others. In fact, [Simon Weppe](https://github.com/simon-msl) has also made a [Docerfile](https://github.com/simon-msl/opendrift/blob/master/docker/Dockerfile) which also includes the NOAA oillibrary, which is needed for oil drift simulations. I guess we can merge these Dockerfiles later.

I would prefer to have the Docker installation instructions in a README-file in a subdirectory instead of the main folder. I can then make a link to it from the [installation instructions](https://github.com/opendrift/opendrift/wiki#download-and-installation).

**Comment by vsoch** [comment]
I'm definitely happy to make these changes! I'll put in some time later today (or this weekend) and update the PR. Thanks for the review!
