### ISSUE TITLE
300% error in seed_elements(radius) to latitude-longitude conversion 

### ISSUE THREAD

**Issue by KKotzak** [OpenDrift/opendrift#81]
When seeding elements with Openoil.seed_elements( radius=A), A is supposed to be meters. But the projection to map coordinates appears to be at least 3*A or 300% wrong.
Example: When seeding at the center of gulf of Mexico with radius 150000m or 150Km particles exceed the sea boundaries and are seeded on the land when Gulf of Mexico is around 1400Km wide West-East and 800Km North-South.

I don't know if meters are wrongly converted in all methods using "distance to map coordinates" conversion or only in the seed_elements method.

**Comment by knutfrode** [comment]
Yes, the unit of radius is meters, but it is interpreted as the standard deviation of a 2D Gaussian distribution around the center point ("uncertainty radius"), and not as an absolute outer bound. Thus elements are seeded more densely near the center than outwards, rather than uniformly within a circle of given radius. 

The documentation is not clear on this, so I will update it.

**Comment by KKotzak** [comment]
Hi Knut-Frode,
Thank you for the reply, yes it makes perfect sense now. So the specified radius contains 68% or 1 sigma (1 standard deviation) of the particles?
Sorry for the false report.
Regard 
Kostas

**Comment by knutfrode** [comment]
Yes, that is correct.
Not a false report, but a useful reminder for me to update the documentation. There are in fact quite a few undocumented features now. So please ask if any questions.
