### ISSUE TITLE
Basemap problem

### ISSUE THREAD

**Issue by sartools** [OpenDrift/opendrift#85]
Hi.
I am trying to install this amazing software.
I think that something is wrong in my brand new installation.

```
ERROR: test_windblow (__main__.TestModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_models.py", line 54, in test_windblow
    o.run(steps=24, time_step=3600)
  File "c:\opendrift\opendrift\opendrift\models\basemodel.py", line 1853, in run
    logging.debug( '  Basemap version %s' % basemap.__version__)
NameError: name 'basemap' is not defined
```
 
Some stuff with Basemap. 
Using windows, python 3.6 and all the libraries required. 

How can I install properly the basemap library?
thanks

**Comment by knutfrode** [comment]
Hi,

Some websites (e.g.  https://github.com/ARM-DOE/pyart/issues/708) indicate that there is (or have been) issues with Basemap for Python 3.6, but apparently it shall be possible to do it with Anaconda, e.g.:
```conda install -c conda-forge basemap```

and then this line to get the high resolution coastline:
```conda install -c conda-forge basemap-data-hires```

I recommend googling Basemap and Python3.6 to find a solution. Otherwise you might need to downgrade to Python 3.5 or Python 2.7 (which most people are still using).
Anyway, if you would like to do oil spill simulations, you need Python 2.7, as the OilLibrary is not yet compliant with Python 3.

**Comment by sartools** [comment]
Thank for this quick answer. 

I will try the option you suggested or create a virtual env.


Thanks 

Enviado desde Correo para Windows 10

De: Knut-Frode Dagestad
Enviado: jueves, 27 de septiembre de 2018 20:48
Para: OpenDrift/opendrift
CC: sartools; Author
Asunto: Re: [OpenDrift/opendrift] Basemap problem (#85)

Hi,
Some websites (e.g. ARM-DOE/pyart#708) indicate that there is (or have been) issues with Basemap for Python 3.6, but apparently it shall be possible to do it with Anaconda, e.g.:
conda install -c conda-forge basemap
and then this line to get the high resolution coastline:
conda install -c conda-forge basemap-data-hires
I recommend googling Basemap and Python3.6 to find a solution. Otherwise you might need to downgrade to Python 3.5 or Python 2.7 (which most people are still using).
Anyway, if you would like to do oil spill simulations, you need Python 2.7, as the OilLibrary is not yet compliant with Python 3.
