### ISSUE TITLE
showing animation and plot

### ISSUE THREAD

**Issue by unalokyay** [OpenDrift/opendrift#90]
Hi All,

I have been trying to run some of the provided examples and display the results as animation and plot. While for some of the examples (e.g. example.py) the animation and plot show up, for others (e.g. leeway.py) they do not show. I can save the plots to file though. 

Kind of related to this issue, trying to save the animations as .mp4 as I cannot visualize them on the fly. it starts grabbing frames, does it for some time then stops doing it with no error or notification.

I'd appreciate any insight on these.

**Comment by unalokyay** [comment]
Hi Knut and thanks for prompt response

unfortunately, for some reason the animation and plot do not display on screen even with no filename is given. I am running on a Windows machine with matplotlib version 2.2.3. Running openDrift from conda environment with python 2.7.15. In fact I downloaded openDrift today

**Comment by knutfrode** [comment]
You say that [example.py](https://github.com/OpenDrift/opendrift/blob/master/examples/example_leeway.py) does show plot/animation to screen, whereas [example_leeway.py](https://github.com/OpenDrift/opendrift/blob/master/examples/example_leeway.py) does not?
Is this systematic, e.g. is it the same each time, even if you run the one script after the other interchangeably?
I have little idea what could cause this, but it might be a Conda or Matplotlib problem, instead of a problem with OpenDrift. Do you have similar plotting/animation problems with other programs than OpenDrift?
I have never used OpenDrift on Windows myself, but I know that several others have, without the problems that you mention.

**Comment by unalokyay** [comment]
That is exactly right and it is the same each time regardless of the order. I am trying other examples as well to figure out. For instance, no display showed for example_macondo.py but example_vietnam.py produced the plot on screen. I did not try creating animation with other programs but had no problem with plotting actually.

**Comment by knutfrode** [comment]
Then we could focus on why the [example_leeway.py](https://github.com/OpenDrift/opendrift/blob/master/examples/example_leeway.py) script does not produce any output.

This tries to animate relatively many frames/timesteps. Can you try to reduce the number of steps from 60*4 to 20 in line 49? If this works, it could indicate insufficient memory available.
What if you more ```o.plot()``` to the line before ```o.animation()```?
Do you otherwise seem to get any other error messages during/after the run?

**Comment by unalokyay** [comment]
I tried them both no change, unfortunately, tried even fewer number of steps; no luck. Does not display plot even I move it before animation. It is actually weird it does not throw any error or warning during or after the run.

**Comment by knutfrode** [comment]
Can you try to comment out lines 33-34 and 46 in ```example_leeway.py```, and see if that makes a difference? (I.e. not adding a basemap-reader explicitly, and not overriding the map projection).
Otherwise you could keep simplifying this script in the direction of ```example.py```

Some Conda-repositories do not include the high and full resolution coastlines, and these have to be installed from a separate package:
https://anaconda.org/conda-forge/basemap-data-hires
However, if this was the case, ```example.py``` should also not work.

**Comment by unalokyay** [comment]
No luck, unfortunately. I have basemap-data-hires installed already as you pointed out the other example would not have worked as well. I will dig a bit deeper and try to see if I can figure it out. Thanks.
That being said any insight from the community will be very much appreciated.

**Comment by vic1309** [comment]
Dear @unalokyay and @knutfrode 

I was facing the same problem reported by @unalokyay . Many others also presented similar issues on Stack Overflow (please see links below). Summarizing, apparently it is related to **Matplotlib backend**, specifically about **'agg'** backend ([Take a look here](https://matplotlib.org/tutorials/introductory/usage.html#non-interactive-example)). According to [Francesco Montesano's answer](https://stackoverflow.com/questions/14558843/why-matplotlib-does-not-plot)):   

> If it is the 'agg' backend, what you see is the expected behaviour as it is a non-interactive backend that does not show anything to the screen, but work with plt.savefig(...)

_How to check which backend is being used?_ 

    >>> import matplotlib 
    >>> matplotlib.get_backend()

_But how do I change it?_

It depends on from where it is being called. According to Matplotlib: 

> This call to matplotlib.use() has no effect because the the backend has already been chosen; matplotlib.use() must be called before pylab, matplotlib.pyplot, or matplotlib.backends is imported for the first time.

Thus, this is related with which **module** is being firstly called. To check if this is your Matplotlib default backend you must open **matplotlibrc** file. To find its path:

    >>> matplotlib.matplotlib_fname() ------- (Probably in line 38)

I found that OpenDrift **basemodel.py** (line 44) and **reader_basemap_landmask.py** (line 26) also call for **'agg'** backend. My solution was to change **'agg'** for **'TkAgg'**.  After that, **reader_x.plot( ), o.plot( ) and o.animation( )** are now being displayed.

There is one more possible solution. At very beginning of your code you may define manually a backend:

    >>>import matplotlib
    >>> matplotlib.use('chosen-backend')

The problem is that you should keep calling it every time you write a new code. Also, if another code has called for 'agg' previously you must restart your prompt and then 'TkAgg' will become your current configuration.  Available backends may be checked [here](https://matplotlib.org/tutorials/introductory/usage.html#backends).


Best wishes,

Victor.

1) [Why Matplotlib does not show plot?](https://stackoverflow.com/questions/14558843/why-matplotlib-does-not-plot)

2) [Matplotlib does not show my drawings although I call pyplot show](https://stackoverflow.com/questions/7534453/matplotlib-does-not-show-my-drawings-although-i-call-pyplot-show)

**Comment by knutfrode** [comment]
Thank you for the good research, Victor.
OpenDrift switches to noninteractive Agg background if no display is available (for batch runs), but apparently this is also activated in your cases, when it should not.
Could it be that you are also running Windows, Victor?

I made now an update which should hopefully solve this problem for Windows machines:
https://github.com/OpenDrift/opendrift/commit/c1d019ff580a2ebee32b3d1df6ccb5003f037e57
