### ISSUE TITLE
Bathymetry plot with Selafin reader

### ISSUE THREAD

**Issue by vincentcasseau** [OpenDrift/opendrift#939]
Hello @Boorhin,

Have you ever tried to plot the bathymetry using the `reader_telemac_selafin` reader?

---

I am following the [_Seafloor interaction_](https://opendrift.github.io/gallery/example_seafloor_interaction.html) test script and would like to plot the `ELEVATION Z` variable, that is correctly mapped to `sea_floor_depth_below_sea_level`.

I edited a few lines like so but it crashes when the `plot` function is called

```python
[...]

start_time = datetime.datetime(2018,7,25,0,0)
proj4_params = '+proj=utm +zone=30 +ellps=WGS84 +datum=WGS84 +units=m +no_defs'

selafin = reader_telemac_selafin.Reader(filename='PATH_TO_SELAFIN_FILE',
                                        proj4=proj4_params,
                                        start_time=start_time)
o.add_reader([selafin])

[... other commands ...]

o.plot(fast=False, background='sea_floor_depth_below_sea_level', show_elements=False)
```

---

The `plot` function calls `get_map_background` in opendrift/models/basemodel.  [`get_map_background`](https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/basemodel.py#L4529-L4594) calls the reader as
```python
data = reader.get_variables(background, time, reader_x, reader_y, None)
```
with the reader method [`get_variables`](https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_telemac_selafin.py#L198-L249) being defined as:
```python
get_variables(self, requested_variables, time=None, x=None, y=None, z=None):
```

#### Issue 1.
The variable `z` is always defaulted to None here and the following line will crash:
```python
# calculate distance from particles to nearest point altitude
idx_layer = np.abs(pm - z).argmin(axis=0)
```

#### Issue 2.
`requested_variables` is not necessarily a np.ndarray or a list. It can be a string, as shown below:
```python
def get_map_background(self, ax, background, crs, time=None):
        # Get background field for plotting on map or animation
        # TODO: this method should be made more robust
        if type(background) is list:
            variable = background[0]  # A vector is requested
        else:
            variable = background  # A scalar is requested

        [...]
        data = reader.get_variables(background, time, reader_x, reader_y, None)
```

causing [this line](https://github.com/OpenDrift/opendrift/blob/master/opendrift/readers/reader_telemac_selafin.py#L232) in `get_variables` to return an error
```python
indices = self.variables == np.array(requested_variables)[:, None]
```
This could easily be fixed by adding these 2 lines at the top of the `get_variables` method:
```python
if type(requested_variables) is str:
    requested_variables = np.array([requested_variables])
```

#### Issue 3.
`get_variables` returns a dictionary, `vars`, initialised as `{}` and with key/value being added as
```python
vars['sea_floor_depth_below_sea_level'] = surface - bottom
# or
vars[requested_variables[i]] = vectors[i]
```
As such, keys `x` and `y` are missing and [the following line](https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/basemodel.py#L4563) in `get_map_background` will crash
```python
reader_x, reader_y = np.meshgrid(data['x'], data['y'])
```

#### Issue 4.
The selafin reader does not have a variable called `projected`, causing the [following line](https://github.com/OpenDrift/opendrift/blob/master/opendrift/models/basemodel.py#L4583) to crash
```python
if reader.projected is False:
    reader_y[reader_y < 0] = 0
    reader_x[reader_x < 0] = 0
```

There might be more issues.

Thanks in advance for your input.
Vincent

**Comment by Boorhin** [comment]
Hi there, 
I have not tried to the plot function recently. I never liked the OpenDrift way of plotting and I use Pyvista for it. I think plotting should be the responsibility of another lib independent from OD.
There might have been an upgrade of OpenDrift since this was coded. In particular with the "projected". 
For issue 1 we can default z to 0, it makes sense. The same was done in any reader I compared with when I wrote that. So it supposedly breaks in all readers?
For issue 2  It seems rather an issue in the core of opendrift? The reader reads information that are formatted in a certain way. When I coded that it was list only. So we would need to ask the advice from the core devs
Issue 3 I don't understand. Selafin files are unstructured grids so meshgrid will make a mess. You cannot infer the topology of an unstructured grid with using the node index. It doesn't make sense. Would you mind developing the idea so I understand?
Issue 4 this didn't exist in the old versions of OD.
It seems to me that you are trying to use a function restricted to structured grids `get_map_background` that is not able to handle unstructured data. I have not had time to follow all the recent developments of OD. I think all the issues you point out, except the defaulting of z to 0 are things linked with the way  `get_map_background` is made.
For performance reasons and as I have transported OpenDrift into the cloud, I have modified my workflow. I transform the [Telemac files into xarray and zarr archives](https://github.com/Boorhin/Telemac3D_to_xarray) and then I have written a xarray reader and a writer for Opendrift. It is very ad-hoc as I have very limited development time and cash at the moment. Works for me... I can update my branches if that's of interest for you, they work with opendrift 1.8. Unfortunately I have not taken the time to try to merge that into the new versions of Opendrift.
Best

**Comment by vincentcasseau** [comment]
Hi Julien,

Thanks a lot, that answers my question.
I agree with you this field could be plotted without resorting to OD and your module, [Telemac3D_to_xarray](https://github.com/Boorhin/Telemac3D_to_xarray), does seem to allow just that. I'll give it a try tomorrow. 

No need to go down the road of solving every issue I pointed out then. As you said, there have been developments in other readers and there are some incompatibilities. It's still very useful to have it for computations.

Thanks for suggesting Pyvista!

I'll get back to you, and I am closing the issue.

Best regards,
Vincent

**Comment by Boorhin** [comment]
Any feedback is welcome, this is only functional with my examples of slf and I have tried to get some traction on the Telemac Forum but had 0 feedback.
Keep me in the loop for needed improvement. 
When your dataset will be in xarray, I think you will notice amazing performance improvements. In particular if you work on a cloud.
Best
