### ISSUE TITLE
Updates over the last six months that might lead to different results?

### ISSUE THREAD

**Issue by calquigs** [OpenDrift/opendrift#944]
Hello!

I've been running some large scale larval dispersal simulations, and I noticed recently that two replications of the same simulation experiment (one that was run recently and one from 6 months ago) returned fairly different results. At first I thought it may have been a function of stochasticity from diffusion (the two runs used different seeds), but when I ran a third replication, the results looked much more similar to the more recent run. This led me to wonder if maybe there had been updates to the model in the last 6 months that could lead to different results. 

I've had a look through the commit history, and the commit I saw that seemed had the best chance of affecting particle trajectories was 4f97b0d93e13218145d2e8674314255aad355cdf from Feb 9 (removed a factor of 2 from diffusion), but I'm not sure if I'm missing something else as well, and I just wanted to double check if there had been other changes since Nov 2021 that could affect trajectories.

Thank you!

**Comment by knutfrode** [comment]
Hi,

The removing of a factor of 2 for diffusion was due to a misunderstanding, and it was reverted in the following commit.
Otherwise, I cannot think of any update that should have a major impact on the drift.

For larvae, I presume that you are using either the LarvalFish or PelagicEgg modules, or some local customization?
Then please note that these should be considered as basic toy/template modules, which users can adapt/improve to their needs (unlike e.g. Leeway and OpenOil which are robustly tested full-fledge modules).
Thus any updates of that specific module could have a large impact (i.e. vertical swimming/buoyancy/mixing).

**Comment by calquigs** [comment]
Thank you for the quick response! I'm running with a custom module, I'll look at the update history there. Cheers!
