### ISSUE TITLE
Representation of openoil viscosity units?

### ISSUE THREAD

**Issue by GilesFearon** [OpenDrift/opendrift#966]
Hi All

I think there may be a couple of discrepancies around how the oil viscosity units are represented in the openoil code.

I see the 'viscosity' units are saved as 'N s/m2 (Pa s)' (line 97 of openoil.py) which would be dynamic viscosity, but it appears the 'viscosity' variable is actually saved and used as kinematic viscosity with units 'm2/s'. So I think the units of the viscosity variable need to changed to 'm2/s' when initialised.

Another small thing I noticed is that the openoil.plot_oil_density_and_viscosity function plots dynamic viscosity, which is computed correctly (dyn_viscosity = kin_viscosity * o.history['density']), however this would have units of 'Pa s' and the ylabel of the plot is shown as [cPoise] / [mPas]. So I think the dyn_viscosity variable should be multiplied by 1000 here to get the correct units for this plot? This also appears in the 'Compare oil budgets' example in the gallery.

Thanks!

**Comment by knutfrode** [comment]
Thank you for this report.
I will look into this next week.

**Comment by knutfrode** [comment]
Indeed, you are right.
The oil property should have been named more explicitly `kinematic_viscosity` instead of simply `viscosity`, to avoid confusion.
Changing this may however have downstream/external consequences, so this should be done in a future major release.
In the meantime I have updated the unit in the description, and in the oil budget plot and the Compare oil budgets example.
https://github.com/OpenDrift/opendrift/commit/bcf8a0cc9ccda3a80a5b4a1ce774eabdc6581aaa
Thanks again for noticing this problem.

**Comment by GilesFearon** [comment]
My pleasure, thanks for following up and for maintaining this fantastic code!
